# Form implementation generated from reading ui file '.\gui\gui.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, files):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 421)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, 16, -1, 16)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setMinimumSize(QtCore.QSize(539, 334))
        self.treeWidget.setAutoExpandDelay(-1)
        self.treeWidget.setIndentation(25)
        self.treeWidget.setUniformRowHeights(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")


        # top level nodes
        for folder in files:
            def make_tree(self, folder):  # folder here is a path to a folder
                root = self.populate(folder)
                self.tree_view.insertTopLevelItem(0, root)

            def populate(self, path):
                tree_item = QTreeWidgetItem()
                tree_item.setText(0, os.path.basename(path))
                for file in os.listdir(path):
                    if os.path.isdir(os.path.join(path, file)):
                        tree_item.addChild(self.populate(os.path.join(path, file)))
                    else:
                        sub_item = QTreeWidgetItem()
                        sub_item .setText(0, file)
                        tree_item.addChild(sub_item )
                return tree_item


        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(200)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(98)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.gridLayout.addWidget(self.treeWidget, 0, 1, 4, 1)
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setStyleSheet("padding-right: 5px;\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"")
        self.uploadButton.setObjectName("uploadButton")
        self.gridLayout.addWidget(self.uploadButton, 0, 0, 1, 1)
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        self.downloadButton.setFont(font)
        self.downloadButton.setStyleSheet("padding-right: 5px;\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"")
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout.addWidget(self.downloadButton, 1, 0, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setStyleSheet("padding-right: 5px;\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"")
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 22))
        self.menubar.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_Key = QtGui.QAction(MainWindow)
        self.actionLoad_Key.setObjectName("actionLoad_Key")
        self.menuFile.addAction(self.actionLoad_Key)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Name"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.uploadButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pick a file to upload to the S3 bucket</p></body></html>"))
        self.uploadButton.setText(_translate("MainWindow", "Upload Files"))
        self.downloadButton.setText(_translate("MainWindow", "Download Files"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLoad_Key.setText(_translate("MainWindow", "Load Key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
