# Form implementation generated from reading ui file '.\gui\login.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(369, 159)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setMinimumSize(QtCore.QSize(369, 159))
        Login.setMaximumSize(QtCore.QSize(369, 159))
        Login.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        Login.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Login)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.accessKeyInput = QtWidgets.QLineEdit(Login)
        self.accessKeyInput.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.accessKeyInput.setClearButtonEnabled(True)
        self.accessKeyInput.setObjectName("accessKeyInput")
        self.gridLayout.addWidget(self.accessKeyInput, 1, 1, 1, 4)
        self.cancel = QtWidgets.QPushButton(Login)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 3, 4, 1, 1)
        self.accessLable = QtWidgets.QLabel(Login)
        self.accessLable.setObjectName("accessLable")
        self.gridLayout.addWidget(self.accessLable, 1, 0, 1, 1)
        self.secretLable = QtWidgets.QLabel(Login)
        self.secretLable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.secretLable.setObjectName("secretLable")
        self.gridLayout.addWidget(self.secretLable, 2, 0, 1, 1)
        self.secretInput = QtWidgets.QLineEdit(Login)
        self.secretInput.setObjectName("secretInput")
        self.gridLayout.addWidget(self.secretInput, 2, 1, 1, 4)
        self.decryptLable = QtWidgets.QLabel(Login)
        self.decryptLable.setObjectName("decryptLable")
        self.gridLayout.addWidget(self.decryptLable, 0, 0, 1, 1)
        self.ok = QtWidgets.QPushButton(Login)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 3, 3, 1, 1)
        self.keyInput = QtWidgets.QLineEdit(Login)
        self.keyInput.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.keyInput.setObjectName("keyInput")
        self.gridLayout.addWidget(self.keyInput, 0, 1, 1, 4)
        self.chooseFile = QtWidgets.QPushButton(Login)
        self.chooseFile.setDefault(True)
        self.chooseFile.setFlat(False)
        self.chooseFile.setObjectName("chooseFile")
        self.gridLayout.addWidget(self.chooseFile, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)
        Login.setTabOrder(self.keyInput, self.accessKeyInput)
        Login.setTabOrder(self.accessKeyInput, self.secretInput)
        Login.setTabOrder(self.secretInput, self.chooseFile)
        Login.setTabOrder(self.chooseFile, self.ok)
        Login.setTabOrder(self.ok, self.cancel)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.cancel.setText(_translate("Login", "Cancel"))
        self.accessLable.setText(_translate("Login", "Access Key"))
        self.secretLable.setText(_translate("Login", "Secrete Key"))
        self.decryptLable.setText(_translate("Login", "Decryption Key"))
        self.ok.setText(_translate("Login", "OK"))
        self.chooseFile.setText(_translate("Login", "Choose File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
